language: ruby
script: bundle exec rake test
sudo: false

rvm:
- "1.9"
- "2.0"
- "2.1"
- "2.2.2"

before_install:
- gem update bundler

gemfile:
- Gemfile.activesupport32
- Gemfile.activesupport40
- Gemfile.activesupport41
- Gemfile.activesupport42
- Gemfile.activesupport50

matrix:
  exclude:
    - rvm: "1.9"
      gemfile: Gemfile.activesupport50
    - rvm: "2.0"
      gemfile: Gemfile.activesupport50
    - rvm: "2.1"
      gemfile: Gemfile.activesupport50
